.\" Copyright (c) 2007 Thomas Hurst <tom@hur.st>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
.\" THE SOFTWARE.
.\"
.Dd October 21, 2007
.Dt K8TEMP 8
.Os
.Sh NAME
.Nm k8temp
.Nd "display on-die temperature readings from AMD K8 processors"
.Sh SYNOPSIS
.Nm
.Op Fl nd
.Op Ar selector ...
|
.Op Fl v | Fl h
.Sh DESCRIPTION
The
.Nm
utility displays temperature readings from AMD K8 processors using
their on-die thermal diode(s).
.Pp
.Nm
requires read-write access to /dev/pci, and thus must be run as root.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl v
Display version and copyright information.
.It Fl h
Display help text.
.It Fl n
Show only temperature values.
.It Fl d
Display debug information, including raw register contents and interpreted subvalues, and
an Advanced Power Management feature dump.
.El
.Pp
Selectors specify which CPU, core and sensor to read, and are of the form
cpu[:core[:sensor]].  Note, output order is fixed, and not (yet) defined by the order of selectors.
.Sh EXAMPLES
.Bl -tag -width -indent
.It k8temp 1:0:0
Display reading for CPU1, core 0, sensor 0.
.It k8temp 1:0
Display reading for CPU1, core 0, all available sensors.
.It k8temp -d 0 2
Display reading for CPU 0 and CPU2, all available cores and sensors.  Display debug output.
.El
.Sh BUGS
.Nm
may cause unsupported systems to reboot, crash or explode.
.Pp
Core numbers on single core systems may be incorrect (e.g. core 1 but no core 0).
.Pp
Running multiple copies of
.Nm
at once could result in readings being taken from incorrect cores.
.Sh HISTORY
.Bl -tag -width indent
.It 0.1.0, 2007-10-21
First release.
.It 0.1.1, 2007-10-22
Fixes a serious error resulting in writes to a bogus PCI register.
.It 0.2.0, 2007-10-25
Add support for diode offset correction and debugging options.  Add CPUID check.
.It 0.3.0, 2007-12-04
Add tenative support for OpenBSD and NetBSD.  Remove (meaningless) diode offset correction.
Introduce value-only output mode and sensor selector arguments.
.El
.Sh SEE ALSO
BIOS and Kernel Developer's Guide for AMD NPT Family 0fh Processors.
Section 4.6.23, Thermtrip Status Register.
.Pp
AMD CPUID Specification, CPUID Fn8000_0007, Advanced Power Management Information.
.Sh AUTHOR
.An "Thomas Hurst" Aq tom@hur.st
